name: Jekyll Themes
description: A directory of the best-looking themes for Jekyll blogs
url: 'https://themes-jekyll.github.io/jekyll-themes'
baseurl: '/jekyllthemes'
github: 'https://github.com/jekyllrc/jekyllthemes'
permalink: /:title/
markdown: rdiscount
gems:
  - jekyll-sitemap
  - jekyll-feed
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
